"""initial schema

Revision ID: 44ae87ce734a
Revises: 
Create Date: 2026-07-01 22:48:49.536281
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ae87ce734a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('remote_image_url', sa.String(length=1024), nullable=True),
    sa.Column('local_image_path', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('downloads_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('estimated_weight_g', sa.Integer(), nullable=True),
    sa.Column('estimated_time_min', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id'),
    sa.UniqueConstraint('source_url')
    )
    with op.batch_alter_table('parsed_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_models_source'), ['source'], unique=False)
        batch_op.create_index('ix_source_downloads', ['source', 'downloads_count'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['parsed_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_model_id'), ['model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_model_id'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_captured_at'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('parsed_models', schema=None) as batch_op:
        batch_op.drop_index('ix_source_downloads')
        batch_op.drop_index(batch_op.f('ix_parsed_models_source'))

    op.drop_table('parsed_models')
    # ### end Alembic commands ###
